### ISSUE TITLE
Doesn't seem to support artifact v4

### ISSUE THREAD

**Issue by dannysauer** [joutvhu/delete-artifact#33]
https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Workflows updated to use the new upload/download v4 format result in "no artifacts found" when running a cleanup action using the delete-artifact action.

Here's an [example failing job](https://github.com/determined-ai/ldap_sync/actions/runs/7589619164).  There is clearly an image.tar artifact present (right now; it may be deleted for future readers), but the action says there was no artifact found.  Once can look at the "download artifact" step in "test_python_compile" this output:
```
Run actions/download-artifact@v4
Downloading single artifact
Preparing to download the following artifacts:
- image.tar (ID: 1182201392, Size: 213437267)
Redirecting to blob download url: https://productionresultssa2.blob.core.windows.net/actions-results/ecff837b-3d83-4b31-9178-5935ada3be25/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/artifacts/image.tar.zip
Starting download of artifact to: /tmp
(node:1675) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Artifact download completed successfully.
Total of 1 artifact(s) downloaded
Download artifact has finished successfully
```
That validates that a second job can download an artifact created by a previous job in the wame workflow.  I wonder if maybe the redirect has something to do with it.  Looking at a [previous job](https://github.com/determined-ai/ldap_sync/actions/runs/7165594669/job/19507954852) using artifact v3, there is no redirect message - the content looks like this:
```
Run actions/download-artifact@v3
Starting download for image.tar
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 1
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Artifact image.tar was downloaded to /tmp
Artifact download has finished successfully
```
It could be that maybe the API call just needs to follow a redirect or something?  I'm not sure.

As an aside, "great job" to Github for exposing the "https://productionresultssa2.blob.core.windows.net" URL. :facepalm:

**Comment by joutvhu** [comment]
Use joutvhu/delete-artifact@v2 for artifact v4
