### ISSUE TITLE
Node.js 12 and "set-output" command are deprecated

### ISSUE THREAD

**Issue by mquinzin** [joutvhu/delete-artifact#9]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

Warning: The "set-output" command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It's great to have non-deprecated examples.

Many thanks.

**Comment by mquinzin** [comment]
Hi, any chance to see this fixed soon ?

**Comment by joutvhu** [comment]
Upgraded to Node.js 16 [https://github.com/joutvhu/delete-artifact/releases/tag/v1.0.2](https://github.com/joutvhu/delete-artifact/releases/tag/v1.0.2)
